dataroot : "<your path to data>"
image_size : 64
batch_size : 1
nc : 3
nz : 100 # Size of z latent vector (i.e. size of generator input)
ngf : 64 # Size of feature maps in generator
ndf : 64 # Size of feature maps in discriminator
alpha : 0.1 # loss ratio of Residual Loss, Discriminator Loss
save_real_img: './test_results/real_image'
save_fake_img: './test_results/fake_images'
netG_checkpoint : '<path to the checkpointG>'
netD_checkpoint : '<path to the checkpointD'